package com.example.ui

/** Centralised string keys for FireCash i18n. Add new keys here and fill both maps in Translations.kt */
object StringKeys {
    // Navigation & general
    const val APP_NAME = "app_name"
    const val HOME = "home"
    const val ANALYTICS = "analytics"
    const val SETTINGS = "settings"
    const val BACK = "back"
    const val DONE = "done"
    const val CANCEL = "cancel"
    const val SAVE = "save"
    const val DELETE = "delete"
    const val SEARCH = "search"
    const val SYNC = "sync"
    const val SYNCING = "syncing"
    const val FORCE_SYNC = "force_sync"
    const val AUTO_SYNC = "auto_sync"

    // Account / home
    const val TOTAL_BALANCE = "total_balance"
    const val MONEY_IN = "money_in"
    const val MONEY_OUT = "money_out"
    const val BANK = "bank"
    const val CASH = "cash"
    const val TRANSACTIONS = "transactions"
    const val NO_TRANSACTIONS = "no_transactions"
    const val SCAN_SLIP = "scan_slip"
    const val ADD_MANUAL = "add_manual"

    // Discovery / empty state
    const val ALL = "all"
    const val SEARCH_TRANSACTIONS = "search_transactions"
    const val NO_MATCHING_SLIPS = "no_matching_slips"
    const val SCAN_SLIP_PROMPT = "scan_slip_prompt"
    const val SEARCH_HELP = "search_help"
    const val SYNCING_SLIPS = "syncing_slips"
    const val UNKNOWN_DATE = "unknown_date"

    // Add transaction dialog
    const val ADD_TRANSACTION = "add_transaction"
    const val AMOUNT_THB = "amount_thb"
    const val EG_AMOUNT = "eg_amount"
    const val NOTE_OPTIONAL = "note_optional"
    const val EG_NOTE = "eg_note"
    const val ADD = "add"
    const val SELECTED = "selected"

    // Verification
    const val VERIFIED = "verified"
    const val UNVERIFIED = "unverified"
    const val DUPLICATE = "duplicate"
    const val RATE_LIMITED = "rate_limited"
    const val AUTH_FAILED = "auth_failed"
    const val SLIP_NOT_FOUND = "slip_not_found"
    const val SCAM_WARNING = "scam_warning"

    // Camera / capture
    const val SCANNING = "scanning"
    const val QR_PAYLOAD = "qr_payload"
    const val PICK_FROM_GALLERY = "pick_from_gallery"
    const val CAPTURE_PHOTO = "capture_photo"

    // Analytics
    const val TRANSACTION_OVERVIEW = "transaction_overview"
    const val TOTAL_SPENT = "total_spent"
    const val AVG_PER_DAY = "avg_per_day"
    const val VS_LAST = "vs_last"
    const val DAY = "day"
    const val WEEK = "week"
    const val MONTH = "month"
    const val YEAR = "year"
    const val INCOME = "income"
    const val OUTCOME = "outcome"
    const val NET = "net"
    const val NO_DATA = "no_data"
    const val AI_INSIGHTS = "ai_insights"
    const val COMPARE_MONTHS = "compare_months"
    const val COMPARE = "compare"

    // Slip detail
    const val AMOUNT = "amount"
    const val DATE = "date"
    const val TIME = "time"
    const val SENDER = "sender"
    const val RECEIVER = "receiver"
    const val TRANS_REF = "trans_ref"
    const val BANK_NAME = "bank_name"
    const val CATEGORY = "category"
    const val WALLET = "wallet"
    const val POSSIBLE_TAMPERED = "possible_tampered"

    // Settings
    const val LANGUAGE = "language"
    const val ENGLISH = "english"
    const val THAI = "thai"
    const val VERIFICATION = "verification"
    const val API_KEY = "api_key"
    const val ENABLED = "enabled"
    const val DISABLED = "disabled"
    const val KNOWN_NAMES = "known_names"
    const val NOTIFICATION_PRESETS = "notification_presets"
    const val TRACKED_FOLDERS = "tracked_folders"
    const val BACKGROUND_LISTENING = "background_listening"
    const val EXPORT_DATA = "export_data"
    const val IMPORT_DATA = "import_data"
    const val ABOUT = "about"

    // SettingsScreen specific
    const val SAFE_SETTINGS = "safe_settings"
    const val MY_NAMES = "my_names"
    const val MY_NAMES_DESC = "my_names_desc"
    const val NAME_PLACEHOLDER = "name_placeholder"
    const val NO_NAMES_YET = "no_names_yet"
    const val REMOVE = "remove"
    const val AUTO_SCAN = "auto_scan"
    const val NO_FOLDERS_YET = "no_folders_yet"
    const val REMOVE_FOLDER = "remove_folder"
    const val ADD_TRACKED_FOLDER = "add_tracked_folder"
    const val SYNC_TRACKED_FOLDERS_NOW = "sync_tracked_folders_now"
    const val FORCE_SYNC_ALL_DESC = "force_sync_all_desc"
    const val IMPORT_SLIP_PHOTOS = "import_slip_photos"
    const val FOLDER_SCAN_DESC = "folder_scan_desc"
    const val KEYWORD_MAPPING = "keyword_mapping"
    const val SMART_TAG = "smart_tag"
    const val KEYWORD_MAPPING_DESC = "keyword_mapping_desc"
    const val REMOVE_RULE = "remove_rule"
    const val ADD_RULE = "add_rule"
    const val DANGEROUS = "dangerous"
    const val TAP_COLLAPSE = "tap_collapse"
    const val TAP_EXPAND = "tap_expand"
    const val BANK_SLIP_VERIFICATION = "bank_slip_verification"
    const val SLIP_VERIFICATION_TITLE = "slip_verification_title"
    const val VERIFY_PROMPTPAY = "verify_promptpay"
    const val API_KEY_LABEL = "api_key_label"
    const val PREVENT_DUPLICATE = "prevent_duplicate"
    const val SYNC_UNVERIFIED_COUNT = "sync_unverified_count"
    const val ADD_API_KEY_SYNC = "add_api_key_sync"
    const val NOTIFICATION_INCOME = "notification_income"
    const val NOTIFICATION_INCOME_DESC = "notification_income_desc"
    const val NOTIFICATION_ACCESS_GRANTED = "notification_access_granted"
    const val ENABLE_NOTIFICATION_ACCESS = "enable_notification_access"
    const val NOTIFICATION_INCOME_HELP = "notification_income_help"
    const val WHITELIST_TITLE = "whitelist_title"
    const val WHITELIST_PREFIX_HELP = "whitelist_prefix_help"
    const val APP_PACKAGE_PLACEHOLDER = "app_package_placeholder"
    const val PREFIX_PLACEHOLDER = "prefix_placeholder"
    const val ADD_TO_WHITELIST = "add_to_whitelist"
    const val NO_WHITELIST = "no_whitelist"
    const val PERMANENT_PRESET = "permanent_preset"
    const val PREFIX_LABEL = "prefix_label"
    const val PREFIX_LABEL_ANY = "prefix_label_any"
    const val NOTIFICATION_EXPENSE = "notification_expense"
    const val NOTIFICATION_EXPENSE_DESC = "notification_expense_desc"
    const val NOTIFICATION_EXPENSE_HELP = "notification_expense_help"
    const val EXPENSE_PREFIX_HELP = "expense_prefix_help"
    const val EXPENSE_PREFIX_PLACEHOLDER = "expense_prefix_placeholder"
    const val BACKGROUND_BATTERY = "background_battery"
    const val BACKGROUND_BATTERY_DESC = "background_battery_desc"
    const val BATTERY_DISABLED_MSG = "battery_disabled_msg"
    const val BATTERY_ENABLED_MSG = "battery_enabled_msg"
    const val KEEP_LISTENING = "keep_listening"
    const val KEEP_LISTENING_DESC = "keep_listening_desc"
    const val DISABLE_BATTERY_OPT = "disable_battery_opt"
    const val DATA_TRANSFER = "data_transfer"
    const val DATA_TRANSFER_DESC = "data_transfer_desc"
    const val EXPORT_JSON = "export_json"
    const val IMPORT_JSON = "import_json"
    const val IMPORT_REPLACE_DESC = "import_replace_desc"
    const val ADD_KEYWORD_MAPPING = "add_keyword_mapping"
    const val MERCHANT_KEYWORD = "merchant_keyword"
    const val MERCHANT_EXAMPLE = "merchant_example"
    const val MAP_TO_CATEGORY = "map_to_category"
    const val CATEGORY_EXAMPLE = "category_example"

    // Slip category
    const val TRANSFER = "transfer"
    const val INCOME_CATEGORY = "income_category"
    const val EXPENSE = "expense"
    const val FOOD_DINING = "food_dining"
    const val TRAVEL = "travel"
    const val RETAIL = "retail"
    const val SOFTWARE = "software"
    const val OFFICE_SUPPLIES = "office_supplies"
    const val OTHER = "other"

    // Misc
    const val MERCHANT = "merchant"
    const val RECEIPT = "receipt"
    const val BANK_SLIP = "bank_slip"
    const val NOT_VERIFIED = "not_verified"
    const val NO_API_KEY = "no_api_key"
    const val VERIFICATION_DISABLED = "verification_disabled"
    const val SLIP_SCANNED = "slip_scanned"
    const val THB = "thb"

    // QrPayloadScreen
    const val NO_PAYLOAD = "no_payload"
    const val COPIED = "copied"
    const val AMOUNT_MISMATCH = "amount_mismatch"
    const val DATE_MISMATCH = "date_mismatch"
    const val SENDER_BANK = "sender_bank"
    const val RECEIVER_BANK = "receiver_bank"
    const val TRANSACTION_REF = "transaction_ref"
    const val AMOUNT_MATCHED = "amount_matched"
    const val YES = "yes"
    const val NO = "no"
    const val STATUS = "status"
    const val SLIP_PHOTO = "slip_photo"
    const val OPEN_PHOTO = "open_photo"
    const val DUPLICATE_SLIP = "duplicate_slip"
    const val SLIP_VERIFIED = "slip_verified"
    const val VERIFICATION_FAILED = "verification_failed"
    const val CLASSIFICATION = "classification"
    const val AUTO_DETECTED = "auto_detected"

    // AnalyticsScreen
    const val NO_DATED_TRANSACTIONS = "no_dated_transactions"
    const val NO_TRANSACTIONS_IN_PERIOD = "no_transactions_in_period"
    const val CURRENT_SUFFIX = "current_suffix"
    const val UP_TO_3_MONTHS = "up_to_3_months"

    // PhotoCaptureScreen
    const val ACCOUNT = "account"
}